# This rule is not used by the project nuclei-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nuclei.homelab.mortenolsen.pro.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nuclei-operator
    app.kubernetes.io/managed-by: kustomize
  name: nucleiscan-admin-role
rules:
- apiGroups:
  - nuclei.homelab.mortenolsen.pro
  resources:
  - nucleiscans
  verbs:
  - '*'
- apiGroups:
  - nuclei.homelab.mortenolsen.pro
  resources:
  - nucleiscans/status
  verbs:
  - get
