# This rule is not used by the project nuclei-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to nuclei.homelab.mortenolsen.pro resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nuclei-operator
    app.kubernetes.io/managed-by: kustomize
  name: nucleiscan-viewer-role
rules:
- apiGroups:
  - nuclei.homelab.mortenolsen.pro
  resources:
  - nucleiscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nuclei.homelab.mortenolsen.pro
  resources:
  - nucleiscans/status
  verbs:
  - get
