# This rule is not used by the project nuclei-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nuclei.homelab.mortenolsen.pro.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nuclei-operator
    app.kubernetes.io/managed-by: kustomize
  name: nucleiscan-editor-role
rules:
- apiGroups:
  - nuclei.homelab.mortenolsen.pro
  resources:
  - nucleiscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nuclei.homelab.mortenolsen.pro
  resources:
  - nucleiscans/status
  verbs:
  - get
