{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nuclei-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nuclei-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "nuclei-operator.selectorLabels" . | nindent 4 }}
{{- end }}